export const fakeData = [
  {
    id: '1',
    wineKr: '도스코파스 까베르네 소비뇽',
    wine: 'Dos Copas Cabernet Sauvignon',
    type: '레드와인',
    image: 'https://penzim.synology.me/image/finalProject/wine_image/1.png',
    sweet: '1',
    acidic: '3',
    body: '3',
    rating: '2.4',
    foodPairing: '소고기, 가금류',
    country: '첼레',
    winery: 'Bodega y Vinedos de Aguirre S.A.',
    grapes: '카베르네 소비뇽',
    alcoholContent: '13',
    wineDescription:
      '진한 붉은색을 띠고 검은 과일이 농축된 듯한 진한 향이 느껴진다. 적절한 산미와 힘이 넘치는 탄닌이 절묘한 균형을 만들어 낸다. 그릴에 구운 육류나, 오리 요리, 불고기등과 좋은 궁합을 보여준다. 칠레의 마울레 밸리의 토양은 화산재와 점토질로 이루어져 있으며, 포도밭의 일조량이 좋아 품질 좋은 포도를 생산하기에 안성맞춤이다.',
  },
  {
    id: '2',
    wineKr: '쌩 클레어 스페셜 에디션 쇼비뇽 블랑',
    wine: 'Saint Clair Special Edition Sauvignon Blanc',
    type: '화이트와인',
    image: 'https://penzim.synology.me/image/finalProject/wine_image/2.png',
    sweet: '1',
    acidic: '3',
    body: '3',
    rating: '3.7',
    foodPairing: '해산물, 치즈, 샐러드',
    country: '뉴질랜드',
    winery: 'Saint Clair Family Estate',
    grapes: '소비뇽블랑',
    alcoholContent: '12',
    wineDescription:
      '밝은 볏짚색을 띠고 있으며 자몽，레몬 제스트，연둣빛 사과 등 상큼한 과일 향과 함께 허브향이 느껴진다. 부드럽게 어우러진 과일 맛이 입 안을 가득 채우며 깔끔한 산미와 함께 긴 여운을 남긴다. 맛과 향이 전체적으로 풍부하고 농도 짙은 스타일을 추구한다.',
  },
  {
    id: '3',
    wineKr: '도스 코파스 레드',
    wine: 'Dos Copas Red Blend',
    type: '레드와인',
    image: 'https://penzim.synology.me/image/finalProject/wine_image/3.png',
    sweet: '2',
    acidic: '2',
    body: '3',
    rating: '2.5',
    foodPairing: '소고기, 돼지고기',
    country: '스페인',
    winery: 'Bodegas Milenium, S.L.',
    grapes: '템프라니요, 가르나차',
    alcoholContent: '12',
    wineDescription:
      '체리와 말린 자두 등 붉은 색 과일 향이 풍부하게 피어 오르고 잘 짜인 구조감과 부드러운 탄닌감이 긴 여운을 남긴다. 붉은 색 육류를 이용한 요리나 신선한 치즈와 함께 마시면 잘 어울린다. 스페인을 대표하는 두 품종인 템프라니요와 가르나차를 블렌딩해 만든 레드와인으로 전형적인 스페인 와인의 특징을 가진다. 풍부한 과실향과 균형 잡힌 맛을 자랑히고 어떤 음식과도 무난하게 잘 어울린다.',
  },
  {
    id: '4',
    wineKr: '올리바레스 띤또',
    wine: 'Olivares Tinto',
    type: '레드와인',
    image: 'https://penzim.synology.me/image/finalProject/wine_image/4.png',
    sweet: '1',
    acidic: '3',
    body: '4',
    rating: '3.4',
    foodPairing: '스테이크,가금류',
    country: '스페인',
    winery: 'Bodegas Olivares S.L.',
    grapes: '레드블랜딩',
    alcoholContent: '14',
    wineDescription:
      '다크 베리류와 체리류의 향이 강하게 느껴지며, 입안에서 블랙 페퍼와 드라이한 허브의 향이 풍부한 와인이다. 잘 익은 과일의 감미로운 맛이 입 안을 가득 채우며 프루티한 매력을 한껏 즐길 수 있는 타입. ',
  },
  {
    id: '5',
    wineKr: '올리바레스 로제',
    wine: 'Olivares Rosado',
    type: '로제와인',
    image: 'https://penzim.synology.me/image/finalProject/wine_image/5.png',
    sweet: '1',
    acidic: '3',
    body: '4',
    rating: '3.6',
    foodPairing: '파스타, 해산물',
    country: '스페인',
    winery: 'Bodegas Olivares S.L.',
    grapes: '가르나차',
    alcoholContent: '13',
    wineDescription:
      '핑크 빛을 띠고 있으며 섬세한 아로마와 은은한 꽃 향기가 느껴지며, 입 안을 개운하게 해 주는 산미가 훌륭하다.',
  },
  {
    id: '6',
    wineKr: '도스 코파스 샤도네이',
    wine: 'Dos Copas Chardonnay',
    type: '화이트와인',
    image: 'https://penzim.synology.me/image/finalProject/wine_image/6.png',
    sweet: '1',
    acidic: '4',
    body: '3',
    rating: '3.1',
    foodPairing: '해산물',
    country: '첼레',
    winery: 'Bodega y Vinedos de Aguirre S.A.',
    grapes: '샤도네이',
    alcoholContent: '13',
    wineDescription:
      '밝은 노란 빛을 띠고 열대 과일의 진한 향이 느껴진다. 복숭아와 파인애플의 맛이 프레시하게 조화를 이루며 지속력이 뛰어나다. 신선한 치즈나 해산물, 그린 샐러드 등과 좋은 궁합을 보여준다. 지중해성 기후와 큰 일교차가특징인 칠레 마울레 밸리의 Villa Alegre 에서 수확한 포도로 풍부한 탄닌과 훌륭한 향이 돋보이는 와인이다',
  },
  {
    id: '7',
    wineKr: '오이스터 베이 쇼비뇽 블랑',
    wine: 'Oyster Bay Sauvignon Blanc',
    type: '화이트와인',
    image: 'https://penzim.synology.me/image/finalProject/wine_image/7.png',
    sweet: '2',
    acidic: '3',
    body: '3',
    rating: '3.8',
    foodPairing: '해산물, 가금류',
    country: '뉴질랜드',
    winery: 'Oyster Bay',
    grapes: '소비뇽블랑',
    alcoholContent: '13',
    wineDescription:
      '반짝이는 초록빛이 감도는 연 노란색에 푸른 사과, 풋풋한 풀 향이 느껴진다. 풍부하고 우아한 아로마가 입안에서 전해지며 산뜻한 산도와 고급스러운 미네랄 터치가 훌륭한 밸런스를 이룬다. 특유의 청량감과 발랄함이 돋보이는 와인으로 뉴질랜드 소비뇽 블랑의 위상을 드높인 와인이다.',
  },
  {
    id: '8',
    wineKr: '올리바레스 블랑코',
    wine: 'Olivares Blanco',
    type: '화이트와인',
    image: 'https://penzim.synology.me/image/finalProject/wine_image/8.png',
    sweet: '1',
    acidic: '3',
    body: '4',
    rating: '3.4',
    foodPairing: '가금류, 샐러드, 해산물, 파스타',
    country: '스페인',
    winery: 'Bodegas Olivares S.L.',
    grapes: '베르데호',
    alcoholContent: '12',
    wineDescription:
      '밝은 볏짚색을 띠고 있으며 깔끔한 시트러스 아로마와 은은한 꽃 향기가 느껴지며 입 안을 개운하게 해 주는 산미가 훌륭하다.',
  },
  {
    id: '9',
    wineKr: '발레벨보 모스까또 다스띠',
    wine: 'Vallebelbo Moscato dAsti',
    type: '스파클링',
    image: 'https://penzim.synology.me/image/finalProject/wine_image/9.png',
    sweet: '5',
    acidic: '5',
    body: '1',
    rating: '3.8',
    foodPairing: '디저트',
    country: '이태리',
    winery: 'Vellebelbo',
    grapes: '모스까또',
    alcoholContent: '12',
    wineDescription:
      '라벨의 그림과 와인의 볏짚 색이 잘 어우러지는와인. 기분좋은 당도와 신선함의 하모니가 두드러지며 과일 향의 향긋함이 인상적이다.',
  },
  {
    id: '10',
    wineKr: '빌라엠 로쏘750ml',
    wine: 'Villa M Rosso',
    type: '스파클링',
    image: 'https://penzim.synology.me/image/finalProject/wine_image/10.png',
    sweet: '4',
    acidic: '2',
    body: '2',
    rating: '4.0',
    foodPairing: '디저트, 샐러드, 과일',
    country: '이태리',
    winery: 'Gianni Gagliardo',
    grapes: '브라케토',
    alcoholContent: '5',
    wineDescription:
      '로맨틱한 붉은 장미 빛깔을 가지고 있으며 부드러운 기포와 잘 익은 붉은 과일향이 매력적인 약 발포성 레드 스위트 와인. 식전주나 간단한 샐러드, 식후 디저트 와인으로 좋으며 달콤한 향과 맛이 디저트류와 환상적인 궁합을 보인다',
  },
];
